### ISSUE TITLE
'critical' messages should be displayed, but are not

### ISSUE THREAD

**Issue by nicrodgers** [consolidation/log#17]
I noticed this running a drush command, which uses the logger.  Critical severity messages are not displayed.

If you run drush -v it is still not displayed.
If you run drush -vvv it is displayed.

**Comment by nicrodgers** [comment]
```
/**
   * Test log levels.
   *
   * @command logtest
   */
  public function logSomething() {
    $this->logger()->emergency('Emergency!');
    $this->logger()->alert('I am an alert ');
    $this->logger()->critical('I am critical ');
    $this->logger()->error('I am an error ');
    $this->logger()->warning('I am a warning ');
    $this->logger()->notice('I am a notice ');
    $this->logger()->info('I am an info message ');
    $this->logger()->debug('I am a debug message ');
  }
```

**Comment by greg-1-anderson** [comment]
This is correct in the verbosity level map:

https://github.com/consolidation/log/blob/2.0.1/src/Logger.php#L217

More isolation, perhaps even a failing test would be helpful.

**Comment by greg-1-anderson** [comment]
Cricital is not represented in https://github.com/consolidation/log/blob/main/tests/LoggerVerbosityAndStyleTests.php

**Comment by greg-1-anderson** [comment]
It took me a really long time to get to this, but I added tests for critical et. al. to the test suite, and they all work fine in this library. Drush has its own logger class that extends the ones here; perhaps it does not have mappings for these log levels.
