### ISSUE TITLE
->success() not advertised in any interface

### ISSUE THREAD

**Issue by donquixote** [consolidation/log#20]
I noticed that the Logger class has a public method `->success()`, which is not advertised in any interface.

This is relevant for drush, where `Drush\Commands\DrushCommands::logger()` returns a `Psr\Log\LoggerInterface` object.
On `$this->logger()->success()`, PhpStorm rightfully complains about "Possible polymorphic call":

> Reports polymorphic code usages. Such usages are ambiguous and can be potentially inoperable depending on the class instance passed as the argument.

Should consolidation/log introduce an "EnhancedLoggerInterface" with additional methods like `->success()`?

**Comment by greg-1-anderson** [comment]
This was introduced to adapt the legacy Drush log levels to the Console logger / PSR-3 logger interface. I think it would be better to remove it from console/log, and let clients add their own log levels rather than formalize it for use by other clients.

@weitzman Do you have any opinion on whether Drush should continue to use the `success` log level?

**Comment by weitzman** [comment]
I'm fine with removing it from Drush.

**Comment by donquixote** [comment]
@weitzman 

> I'm fine with removing it from Drush.

Drush shows the green " [success] " for ->success() messages.
I assume this is a feature that people like and expect?

I don't have a clear opinion about it. For me it becomes relevant when colleagues or myself use this in our own drush commands, and we get IDE inspection warnings.

Even if we remove its usage in Drush core, it will still be used in contrib and custom code.

I wonder, could we insert an interface without BC break?
Currently, DrushCommands->logger() is annotated to return a PSR logger. There is no native code type hint.
Adding a native code type hint would be a hard BC break for subclasses of DrushCommands that override ->logger().
But adding it in PhpDoc would only make IDEs think something is wrong.

**Comment by weitzman** [comment]
Good point about the green success message. I do think people use and enjoy that. An intermediate interface works for me. Any thoughts @greg-1-anderson?

**Comment by greg-1-anderson** [comment]
> Adding a native code type hint would be a hard BC break for subclasses of DrushCommands that override ->logger()

Yeah changing the typehint of DrushCommands is technically a BC break and probably shouldn't be done until the next major version of Drush. In practice, though, it should be pretty rare to override `logger()`, so I don't think that we'd be making a lot of extra work for folks getting their extensions working in Drush 11 if we did it.

My preference would be:
- Remove `success` from the next major version of consolidation/log
- Add `success` with a new interface in Drush 11
- Make the DrushCommands `logger` method return a class or interface that implements both `Psr\Log\LoggerInterface` and the success interface.

I think that doing this would be fairly straightforward.

**Comment by weitzman** [comment]
Drush PR at https://github.com/drush-ops/drush/pull/5003. I think it does what is described here. I can follow-up with a PR in this repo.

**Comment by weitzman** [comment]
As an aside, I'm interested in a plan which describes how to make the Drush logger configurable by sites (e.g. use Monolog).

**Comment by greg-1-anderson** [comment]
Looks good to me. Do you need a new major release of consolidation/log without the `success()` method?

Regarding configurable loggers in Drush, it's not possible for a Drush extension to modify Drush's DI container. Therefore, if we wanted the Drush logger to be replaceable, we'd need to instantiate a delegate logger in the DI container, and set it to call through to the Drush logger. Then, we'd need an API to reconfigure the delegate logger, to replace or compliment the Drush logger with a user-supplied PSR-3 logger.

**Comment by weitzman** [comment]
I merged the Drush PR. Not sure when I might work on a PR for this repo.
